CREATE DATABASE BD_BIB;
USE BD_BIB;

CREATE TABLE ALUMNOS
(
	NRO_CONTROL VARCHAR(14),
    NOM_ALUMNO VARCHAR(50),
    APE_PAT_ALUMNO VARCHAR(50),
    APE_MAT_ALUMNO VARCHAR(50),
    GPO_ALUMNO VARCHAR(50),
    TNO_ALUMNO VARCHAR(50),
    CRA_ALUMNO VARCHAR(50),
    GRO_ALUMNO VARCHAR(50),
    CORREO_ALUMNO VARCHAR(60),
    
    PRIMARY KEY (NRO_CONTROL)
);
CREATE TABLE DOCENTES
(
	RFC_DOCENTE CHAR(13) NOT NULL,
    NOM_COM_DOCENTE VARCHAR(50),
    CORREO_DOCENTE VARCHAR(50),
    GRO_DOCENTE CHAR(1),

    PRIMARY KEY (RFC_DOCENTE)
);
CREATE TABLE USUARIOS
(
	ID_USUARIO VARCHAR(50) NOT NULL,
    NOM_USUARIO VARCHAR(50),
    APE_PAT_USUARIO VARCHAR(50),
    APE_MAT_USUARIO VARCHAR(50),
    TEL_USUARIO CHAR(10),
    CONTRA_USUARIO VARCHAR(20),
    TNO_USUARIO VARCHAR(10),
    
    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE LIBROS
(
	COD_LIBRO INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    CAMPO_DISCIPLINAR VARCHAR(100),
    ASIGNATURA VARCHAR (100),
    NUM_LIBRO VARCHAR(100),
    NOM_LIBRO VARCHAR(100),
    AU_LIBRO VARCHAR(100),
    PAG_LIBRO VARCHAR(100),
    AÑO_LUGAR_IMPRESION VARCHAR (100),
    EDITORIAL VARCHAR (100),
    
    PRIMARY KEY (COD_LIBRO)
);

CREATE TABLE PRESTAMO
(
	COD_PRESTAMO INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    NRO_CONTROL_PRES CHAR(14),
    RFC_DOCENTE_PRES CHAR(13),
    ID_USUARIO_PRES VARCHAR(50),
    FECHA_PRES DATE,
    FECHA_DEV DATE,
    ESTADO_DEV BOOLEAN,
    COD_LIBRO_PRES INT(10) ZEROFILL,
    
    PRIMARY KEY (COD_PRESTAMO),
    FOREIGN KEY (RFC_DOCENTE_PRES) REFERENCES DOCENTES(RFC_DOCENTE),
    FOREIGN KEY (NRO_CONTROL_PRES) REFERENCES ALUMNOS(NRO_CONTROL),
    FOREIGN KEY (ID_USUARIO_PRES) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (COD_LIBRO_PRES) REFERENCES LIBROS(COD_LIBRO)
);

CREATE TABLE VISITAS
(
	NUM_VISITA INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    NRO_CONTROL_VISITA CHAR(14),
    RFC_DOCENTE_VISITA CHAR(13),
    FECHA_VISITA DATE,
    HORA_VISITA TIME,
    TIPO_VISITA VARCHAR(50),
    
    PRIMARY KEY (NUM_VISITA),
    FOREIGN KEY (NRO_CONTROL_VISITA) REFERENCES ALUMNOS(NRO_CONTROL),
    FOREIGN KEY (RFC_DOCENTE_VISITA) REFERENCES DOCENTES(RFC_DOCENTE)
);
CREATE TABLE ASESORIAS
(
	NUM_ASESORIA INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    NRO_CONTROL_ASESORADO CHAR(14),
    RFC_DOCENTE_ASESOR CHAR(13),
    NRO_CONTROL_ASESOR CHAR(14),
    FECHA_ASESORIA DATE,
    CUBICULO VARCHAR(20),
    
    PRIMARY KEY (NUM_ASESORIA),
    FOREIGN KEY (NRO_CONTROL_ASESORADO) REFERENCES ALUMNOS(NRO_CONTROL),
    FOREIGN KEY (NRO_CONTROL_ASESOR) REFERENCES ALUMNOS(NRO_CONTROL),
    FOREIGN KEY (RFC_DOCENTE_ASESOR) REFERENCES DOCENTES(RFC_DOCENTE)
);

CREATE TABLE DEVOLUCION
(
	COD_DEV INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
    NRO_CONTROL_DEV CHAR(14),
    RFC_DOCENTE_DEV CHAR(13),
    ID_USUARIO_DEV VARCHAR(50),
    FECHA_DEV DATE,
    
    PRIMARY KEY (COD_DEV),
    FOREIGN KEY (RFC_DOCENTE_DEV) REFERENCES DOCENTES(RFC_DOCENTE),
    FOREIGN KEY (NRO_CONTROL_DEV) REFERENCES ALUMNOS(NRO_CONTROL),
    FOREIGN KEY (ID_USUARIO_DEV) REFERENCES USUARIOS(ID_USUARIO)
);
